import { prisma } from '../../../core/database/prisma';
import { AppError } from '../../../core/errors/app-error';

export type CommunicationChannel = 'WHATSAPP' | 'SMS' | 'EMAIL' | 'IN_APP';
export type DeliveryStatus = 'QUEUED' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED';
export type NotificationCategory = 'ACCOUNTS' | 'PURCHASE' | 'SALES' | 'SYSTEM' | 'AUDIT';

export interface MessageTemplate {
  id: string;
  name: string;
  channel: CommunicationChannel;
  category: NotificationCategory;
  subject?: string;
  body: string;
  variables: string[];
}

export interface CommunicationLog {
  id: string;
  tenantId: string;
  channel: CommunicationChannel;
  category: NotificationCategory;
  recipientName: string;
  recipientContact: string;
  templateId?: string;
  subject?: string;
  content: string;
  status: DeliveryStatus;
  sentAt: string;
  deliveredAt?: string;
  readAt?: string;
  errorMessage?: string;
  metadata?: Record<string, any>;
}

export interface InAppNotification {
  id: string;
  tenantId: string;
  userId?: string;
  category: NotificationCategory;
  title: string;
  message: string;
  isRead: boolean;
  actionUrl?: string;
  createdAt: string;
}

export interface SendMessageDto {
  tenantId?: string;
  userId?: string;
  channel: CommunicationChannel;
  category?: NotificationCategory;
  recipientName: string;
  recipientContact: string;
  templateId?: string;
  subject?: string;
  content?: string;
  templateVariables?: Record<string, any>;
  metadata?: Record<string, any>;
}

export const SYSTEM_TEMPLATES: MessageTemplate[] = [
  {
    id: 'tmpl-inv-dispatch-wa',
    name: 'Sales Tax Invoice Dispatch',
    channel: 'WHATSAPP',
    category: 'SALES',
    body: 'Dear {{partyName}},\n\nYour Tax Invoice #{{docNumber}} dated {{date}} for ₹{{amount}} has been generated by {{companyName}}. Please find your digitally signed invoice attached.\n\nThank you for your business!\n— {{companyName}} Accounting',
    variables: ['partyName', 'docNumber', 'date', 'amount', 'companyName'],
  },
  {
    id: 'tmpl-po-approval-email',
    name: 'Purchase Order Approval Request',
    channel: 'EMAIL',
    category: 'PURCHASE',
    subject: 'Action Required: Purchase Order #{{docNumber}} Pending Approval',
    body: 'Dear {{partyName}},\n\nPurchase Order #{{docNumber}} for {{amount}} has been submitted by the procurement department and requires your executive sign-off under MCA 4-Eyes policy.\n\nKindly review and approve inside Finstaq.\n\nRegards,\nFinstaq Workflow Engine',
    variables: ['partyName', 'docNumber', 'amount'],
  },
  {
    id: 'tmpl-payment-receipt-sms',
    name: 'Payment Receipt Confirmation',
    channel: 'SMS',
    category: 'ACCOUNTS',
    body: 'Apex Industries: Received ₹{{amount}} against Voucher {{docNumber}} on {{date}}. Updated ledger balance is updated. TxnRef: {{partyName}}.',
    variables: ['amount', 'docNumber', 'date', 'partyName'],
  },
  {
    id: 'tmpl-due-payment-wa',
    name: 'Outstanding Balance Payment Reminder',
    channel: 'WHATSAPP',
    category: 'ACCOUNTS',
    body: 'Gentle Reminder from {{companyName}}:\n\nOutstanding balance of ₹{{amount}} on Invoice #{{docNumber}} is due for payment. Kindly arrange remittance via NEFT/RTGS or UPI.\n\nThank you,\nFinance & Accounts Team',
    variables: ['companyName', 'amount', 'docNumber'],
  },
  {
    id: 'tmpl-salary-slip-sms',
    name: 'Salary Credit & Payslip Notification',
    channel: 'SMS',
    category: 'ACCOUNTS',
    body: 'Dear {{partyName}}, your salary for {{date}} has been credited to your bank account (Net Pay: ₹{{amount}}). Your password-protected payslip is available in Finstaq ESS Portal.',
    variables: ['partyName', 'date', 'amount'],
  },
  {
    id: 'tmpl-gstr1-filed-email',
    name: 'GSTR-1 Statutory Filing Confirmation',
    channel: 'EMAIL',
    category: 'AUDIT',
    subject: 'Compliance Notice: GSTR-1 Return Successfully Filed (ARN: {{docNumber}})',
    body: 'Dear Tax Team,\n\nThe GSTR-1 return for the tax period has been successfully transmitted and acknowledged by the GSTN Portal under ARN: {{docNumber}} for {{companyName}}.\n\nSummary total taxable value: ₹{{amount}}.\n\nStatus: 100% Validated.',
    variables: ['docNumber', 'companyName', 'amount'],
  },
  {
    id: 'tmpl-low-stock-inapp',
    name: 'Critical Inventory Stock Level Alert',
    channel: 'IN_APP',
    category: 'PURCHASE',
    subject: 'Critical Low Stock Warning: {{docNumber}}',
    body: 'Current inventory for {{docNumber}} has fallen below minimum safety buffer (Valued at ₹{{amount}}). Auto-reorder suggestion triggered for procurement.',
    variables: ['docNumber', 'amount'],
  },
];

const DEFAULT_SEED_LOGS: CommunicationLog[] = [
  {
    id: 'log-seed-01',
    tenantId: '27AABCF1234F1Z5',
    channel: 'WHATSAPP',
    category: 'SALES',
    recipientName: 'Tata Motors Limited',
    recipientContact: '+91 98234 56789',
    templateId: 'tmpl-inv-dispatch-wa',
    subject: undefined,
    content: 'Dear Tata Motors Limited, Your Tax Invoice #INV-2026-089 dated 18-Sep-2026 for ₹16,50,000.00 has been generated by Apex Industries Ltd. Thank you for your business!',
    status: 'READ',
    sentAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 2 + 3000).toISOString(),
    readAt: new Date(Date.now() - 3600000 * 1.5).toISOString(),
  },
  {
    id: 'log-seed-02',
    tenantId: '27AABCF1234F1Z5',
    channel: 'EMAIL',
    category: 'PURCHASE',
    recipientName: 'Director of Procurement',
    recipientContact: 'procurement@apex.finstaq.com',
    templateId: 'tmpl-po-approval-email',
    subject: 'Action Required: Purchase Order #PO-2026-042 Pending Approval',
    content: 'Purchase Order #PO-2026-042 for ₹3,48,000.00 has been submitted and requires executive sign-off.',
    status: 'DELIVERED',
    sentAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 5 + 4000).toISOString(),
  },
  {
    id: 'log-seed-03',
    tenantId: '27AABCF1234F1Z5',
    channel: 'SMS',
    category: 'ACCOUNTS',
    recipientName: 'Kirloskar Oil Engines',
    recipientContact: '+91 94220 12345',
    templateId: 'tmpl-payment-receipt-sms',
    content: 'Apex Industries: Received ₹8,45,200.00 against Voucher RCT-2026-104 on 19-Sep-2026. Updated ledger balance reflected.',
    status: 'DELIVERED',
    sentAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 12 + 2000).toISOString(),
  },
  {
    id: 'log-seed-04',
    tenantId: '27AABCF1234F1Z5',
    channel: 'IN_APP',
    category: 'AUDIT',
    recipientName: 'Finance Admin',
    recipientContact: 'admin@apex.finstaq.com',
    templateId: 'tmpl-low-stock-inapp',
    subject: 'Critical Low Stock Warning: CR-SHEET-2MM',
    content: 'Current inventory for CR-SHEET-2MM has fallen below minimum safety buffer. Auto-reorder PO draft created.',
    status: 'READ',
    sentAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 24 + 1000).toISOString(),
  },
];

async function getTenantLogs(tenantId: string): Promise<CommunicationLog[]> {
  const record = await prisma.keyValueStore.findUnique({
    where: { tenantId_key: { tenantId, key: 'COMM_LOGS' } },
  });
  if (record && record.value && Array.isArray(record.value) && record.value.length > 0) {
    return record.value as unknown as CommunicationLog[];
  }
  const seed = DEFAULT_SEED_LOGS.map(l => ({ ...l, tenantId }));
  try {
    await prisma.keyValueStore.upsert({
      where: { tenantId_key: { tenantId, key: 'COMM_LOGS' } },
      update: { value: seed as any },
      create: { tenantId, key: 'COMM_LOGS', value: seed as any },
    });
  } catch (e) {
    // Ignore race
  }
  return seed;
}

async function saveTenantLogs(tenantId: string, logs: CommunicationLog[]) {
  await prisma.keyValueStore.upsert({
    where: { tenantId_key: { tenantId, key: 'COMM_LOGS' } },
    update: { value: logs as any },
    create: { tenantId, key: 'COMM_LOGS', value: logs as any },
  });
}

async function getTenantNotifs(tenantId: string): Promise<InAppNotification[]> {
  const record = await prisma.keyValueStore.findUnique({
    where: { tenantId_key: { tenantId, key: 'COMM_NOTIFS' } },
  });
  if (record && record.value && Array.isArray(record.value)) {
    return record.value as unknown as InAppNotification[];
  }
  const arr: InAppNotification[] = [];
  try {
    await prisma.keyValueStore.create({ data: { tenantId, key: 'COMM_NOTIFS', value: arr as any } });
  } catch (e) {
    // Ignore race
  }
  return arr;
}

async function saveTenantNotifs(tenantId: string, notifs: InAppNotification[]) {
  await prisma.keyValueStore.upsert({
    where: { tenantId_key: { tenantId, key: 'COMM_NOTIFS' } },
    update: { value: notifs as any },
    create: { tenantId, key: 'COMM_NOTIFS', value: notifs as any },
  });
}

export class CommunicationService {
  /**
   * Retrieves all pre-configured communication templates
   */
  public static async getTemplates(): Promise<MessageTemplate[]> {
    return SYSTEM_TEMPLATES;
  }

  /**
   * Dispatches a multi-channel message (WhatsApp, SMS, Email, In-App)
   */
  public static async sendMessage(dto: SendMessageDto): Promise<CommunicationLog> {
    const tenantId = dto.tenantId || '27AABCF1234F1Z5';
    let finalContent = dto.content || '';
    let finalSubject = dto.subject;

    // Merge template if templateId provided
    if (dto.templateId) {
      const template = SYSTEM_TEMPLATES.find((t) => t.id === dto.templateId);
      if (template) {
        finalContent = template.body;
        finalSubject = template.subject;
        if (dto.templateVariables) {
          Object.entries(dto.templateVariables).forEach(([key, val]) => {
            const regex = new RegExp(`\\{\\{\\s*${key}\\s*\\}\\}`, 'g');
            finalContent = finalContent.replace(regex, String(val));
            if (finalSubject) {
              finalSubject = finalSubject.replace(regex, String(val));
            }
          });
        }
      }
    }

    if (!finalContent.trim()) {
      throw new AppError('Message content cannot be empty', 400);
    }

    const logEntry: CommunicationLog = {
      id: `log-${Date.now()}`,
      tenantId,
      channel: dto.channel,
      category: dto.category || 'SYSTEM',
      recipientName: dto.recipientName,
      recipientContact: dto.recipientContact,
      templateId: dto.templateId,
      subject: finalSubject,
      content: finalContent,
      status: 'SENT',
      sentAt: new Date().toISOString(),
      deliveredAt: new Date(Date.now() + 1200).toISOString(),
      metadata: dto.metadata,
    };

    const logs = await getTenantLogs(tenantId);
    logs.unshift(logEntry);
    await saveTenantLogs(tenantId, logs);

    // If channel is IN_APP, create notification record
    if (dto.channel === 'IN_APP') {
      const notif: InAppNotification = {
        id: `notif-${Date.now()}`,
        tenantId,
        userId: dto.userId,
        category: dto.category || 'SYSTEM',
        title: finalSubject || 'System Alert',
        message: finalContent,
        isRead: false,
        actionUrl: dto.metadata?.actionUrl,
        createdAt: new Date().toISOString(),
      };
      const notifs = await getTenantNotifs(tenantId);
      notifs.unshift(notif);
      await saveTenantNotifs(tenantId, notifs);
    }

    return logEntry;
  }

  /**
   * Retrieves communication dispatch logs
   */
  public static async getLogs(query: {
    tenantId: string;
    channel?: CommunicationChannel;
    category?: NotificationCategory;
    status?: DeliveryStatus;
  }): Promise<CommunicationLog[]> {
    const logs = await getTenantLogs(query.tenantId || '27AABCF1234F1Z5');
    return logs.filter((l) => {
      if (query.channel && l.channel !== query.channel) return false;
      if (query.category && l.category !== query.category) return false;
      if (query.status && l.status !== query.status) return false;
      return true;
    });
  }

  /**
   * Retrieves in-app notifications
   */
  public static async getNotifications(tenantId: string): Promise<{
    unreadCount: number;
    notifications: InAppNotification[];
  }> {
    const notifs = await getTenantNotifs(tenantId || '27AABCF1234F1Z5');
    const unreadCount = notifs.filter((n) => !n.isRead).length;
    return { unreadCount, notifications: notifs };
  }

  /**
   * Marks a notification as read
   */
  public static async markAsRead(tenantId: string, notifId: string): Promise<boolean> {
    const notifs = await getTenantNotifs(tenantId || '27AABCF1234F1Z5');
    const item = notifs.find((n) => n.id === notifId);
    if (item) {
      item.isRead = true;
      await saveTenantNotifs(tenantId, notifs);
      return true;
    }
    return false;
  }

  /**
   * Marks all notifications as read
   */
  public static async markAllAsRead(tenantId: string): Promise<number> {
    let count = 0;
    const notifs = await getTenantNotifs(tenantId || '27AABCF1234F1Z5');
    notifs.forEach((n) => {
      if (!n.isRead) {
        n.isRead = true;
        count++;
      }
    });
    if (count > 0) {
      await saveTenantNotifs(tenantId, notifs);
    }
    return count;
  }

  /**
   * Directly creates an in-app notification
   */
  public static async createInAppNotification(data: {
    tenantId: string;
    userId?: string;
    category?: NotificationCategory;
    title: string;
    message: string;
    actionUrl?: string;
  }): Promise<InAppNotification> {
    const notif: InAppNotification = {
      id: `notif-${Date.now()}`,
      tenantId: data.tenantId,
      userId: data.userId,
      category: data.category || 'SYSTEM',
      title: data.title,
      message: data.message,
      isRead: false,
      actionUrl: data.actionUrl,
      createdAt: new Date().toISOString(),
    };
    const notifs = await getTenantNotifs(data.tenantId);
    notifs.unshift(notif);
    await saveTenantNotifs(data.tenantId, notifs);
    return notif;
  }
}
