import React, { useState, useEffect, useMemo } from 'react';
import { useAuth } from '../../context/AuthContext';
import { 
  Send, MessageSquare, Mail, Smartphone, Bell, CheckCircle2, 
  Clock, AlertCircle, RefreshCw, FileText, Check, Copy, UserCheck, Search, Filter,
  Sparkles, Layers, ShieldCheck, ArrowRight, RotateCcw, ChevronRight, Eye, Zap,
  CheckCheck
} from 'lucide-react';
import { useToast } from '../../context/ToastContext';
import { useConfirm } from '../../context/ConfirmContext';
import { KPIGrid, KPIScorecard } from '../common/KPIScorecard';
import { StandardTabs } from '../common/StandardTabs';

export interface CommTemplate {
  id: string;
  name: string;
  channel: 'whatsapp' | 'sms' | 'email' | 'in_app';
  category?: string;
  subject?: string;
  body?: string;
  content?: string;
  variables: string[];
}

export interface CommLog {
  id: string;
  tenantId?: string;
  channel: 'whatsapp' | 'sms' | 'email' | 'in_app';
  recipient?: string;
  recipientName?: string;
  recipientContact?: string;
  subject?: string;
  content: string;
  status: 'queued' | 'sent' | 'delivered' | 'read' | 'failed';
  referenceType?: string;
  referenceId?: string;
  sentAt: string;
  deliveredAt?: string;
  error?: string;
}

const DEFAULT_FALLBACK_TEMPLATES: CommTemplate[] = [
  {
    id: 'tmpl-inv-dispatch-wa',
    name: 'Sales Tax Invoice Dispatch',
    channel: 'whatsapp',
    category: 'SALES',
    body: 'Dear {{partyName}},\n\nYour Tax Invoice #{{docNumber}} dated {{date}} for ₹{{amount}} has been generated by {{companyName}}. Please find your digitally signed invoice attached.\n\nThank you for your business!\n— {{companyName}} Accounting',
    variables: ['partyName', 'docNumber', 'date', 'amount', 'companyName'],
  },
  {
    id: 'tmpl-po-approval-email',
    name: 'Purchase Order Approval Request',
    channel: 'email',
    category: 'PURCHASE',
    subject: 'Action Required: Purchase Order #{{docNumber}} Pending Approval',
    body: 'Dear {{partyName}},\n\nPurchase Order #{{docNumber}} for ₹{{amount}} has been submitted by the procurement department and requires your executive sign-off under MCA 4-Eyes policy.\n\nKindly review and approve inside Finstaq.\n\nRegards,\nFinstaq Workflow Engine',
    variables: ['partyName', 'docNumber', 'amount'],
  },
  {
    id: 'tmpl-payment-receipt-sms',
    name: 'Payment Receipt Confirmation',
    channel: 'sms',
    category: 'ACCOUNTS',
    body: 'Apex Industries: Received ₹{{amount}} against Voucher {{docNumber}} on {{date}}. Updated ledger balance is updated. TxnRef: {{partyName}}.',
    variables: ['amount', 'docNumber', 'date', 'partyName'],
  },
  {
    id: 'tmpl-due-payment-wa',
    name: 'Outstanding Balance Payment Reminder',
    channel: 'whatsapp',
    category: 'ACCOUNTS',
    body: 'Gentle Reminder from {{companyName}}:\n\nOutstanding balance of ₹{{amount}} on Invoice #{{docNumber}} is due for payment. Kindly arrange remittance via NEFT/RTGS or UPI.\n\nThank you,\nFinance & Accounts Team',
    variables: ['companyName', 'amount', 'docNumber'],
  },
  {
    id: 'tmpl-salary-slip-sms',
    name: 'Salary Credit & Payslip Notification',
    channel: 'sms',
    category: 'ACCOUNTS',
    body: 'Dear {{partyName}}, your salary for {{date}} has been credited to your bank account (Net Pay: ₹{{amount}}). Your password-protected payslip is available in Finstaq ESS Portal.',
    variables: ['partyName', 'date', 'amount'],
  },
  {
    id: 'tmpl-gstr1-filed-email',
    name: 'GSTR-1 Statutory Filing Confirmation',
    channel: 'email',
    category: 'AUDIT',
    subject: 'Compliance Notice: GSTR-1 Return Successfully Filed (ARN: {{docNumber}})',
    body: 'Dear Tax Team,\n\nThe GSTR-1 return for the tax period has been successfully transmitted and acknowledged by the GSTN Portal under ARN: {{docNumber}} for {{companyName}}.\n\nSummary total taxable value: ₹{{amount}}.\n\nStatus: 100% Validated.',
    variables: ['docNumber', 'companyName', 'amount'],
  },
  {
    id: 'tmpl-low-stock-inapp',
    name: 'Critical Inventory Stock Level Alert',
    channel: 'in_app',
    category: 'PURCHASE',
    subject: 'Critical Low Stock Warning: {{docNumber}}',
    body: 'Current inventory for {{docNumber}} has fallen below minimum safety buffer (Valued at ₹{{amount}}). Auto-reorder suggestion triggered for procurement.',
    variables: ['docNumber', 'amount'],
  },
];

const DEFAULT_FALLBACK_LOGS: CommLog[] = [
  {
    id: 'log-01',
    channel: 'whatsapp',
    recipient: '+91 98234 56789 (Tata Motors Ltd)',
    recipientName: 'Tata Motors Limited',
    recipientContact: '+91 98234 56789',
    content: 'Dear Tata Motors Limited, Your Tax Invoice #INV-2026-089 dated 18-Sep-2026 for ₹16,50,000.00 has been generated by Apex Industries Ltd. Digitally signed invoice attached.',
    status: 'read',
    sentAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 2 + 3000).toISOString(),
  },
  {
    id: 'log-02',
    channel: 'email',
    recipient: 'procurement@apex.finstaq.com (Director of Procurement)',
    recipientName: 'Director of Procurement',
    recipientContact: 'procurement@apex.finstaq.com',
    subject: 'Action Required: Purchase Order #PO-2026-042 Pending Approval',
    content: 'Purchase Order #PO-2026-042 for ₹3,48,000.00 has been submitted and requires executive sign-off.',
    status: 'delivered',
    sentAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 5 + 4000).toISOString(),
  },
  {
    id: 'log-03',
    channel: 'sms',
    recipient: '+91 94220 12345 (Kirloskar Oil Engines)',
    recipientName: 'Kirloskar Oil Engines',
    recipientContact: '+91 94220 12345',
    content: 'Apex Industries: Received ₹8,45,200.00 against Voucher RCT-2026-104 on 19-Sep-2026. Updated ledger balance reflected.',
    status: 'delivered',
    sentAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    deliveredAt: new Date(Date.now() - 3600000 * 12 + 2000).toISOString(),
  },
  {
    id: 'log-04',
    channel: 'in_app',
    recipient: 'admin@apex.finstaq.com (Finance Admin)',
    recipientName: 'Finance Admin',
    recipientContact: 'admin@apex.finstaq.com',
    subject: 'Critical Low Stock Warning: CR-SHEET-2MM',
    content: 'Current inventory for CR-SHEET-2MM has fallen below minimum safety buffer. Auto-reorder PO draft created.',
    status: 'read',
    sentAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];

export const CommunicationHub: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'send' | 'logs' | 'templates'>('send');
  const [channel, setChannel] = useState<'whatsapp' | 'sms' | 'email' | 'in_app'>('whatsapp');
  const [recipient, setRecipient] = useState('');
  const [subject, setSubject] = useState('');
  const [content, setContent] = useState('');
  const [selectedTemplateId, setSelectedTemplateId] = useState('');
  
  const [templates, setTemplates] = useState<CommTemplate[]>(DEFAULT_FALLBACK_TEMPLATES);
  const [logs, setLogs] = useState<CommLog[]>(DEFAULT_FALLBACK_LOGS);
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [searchLog, setSearchLog] = useState('');
  const [logChannelFilter, setLogChannelFilter] = useState<string>('all');
  const [searchTemplate, setSearchTemplate] = useState('');

  const { success, error, info, warning } = useToast();
  const { getAuthHeaders } = useAuth();
  const { confirm } = useConfirm();

  const normalizeTemplate = (t: any): CommTemplate => {
    const rawChannel = (t.channel || 'whatsapp').toLowerCase();
    const validChannel: 'whatsapp' | 'sms' | 'email' | 'in_app' = 
      rawChannel === 'in_app' || rawChannel === 'inapp' ? 'in_app' :
      rawChannel === 'email' ? 'email' :
      rawChannel === 'sms' ? 'sms' : 'whatsapp';

    return {
      id: t.id,
      name: t.name,
      channel: validChannel,
      category: t.category,
      subject: t.subject,
      body: t.body || t.content || '',
      content: t.content || t.body || '',
      variables: Array.isArray(t.variables) ? t.variables : [],
    };
  };

  const normalizeLog = (l: any): CommLog => {
    const rawChannel = (l.channel || 'whatsapp').toLowerCase();
    const validChannel: 'whatsapp' | 'sms' | 'email' | 'in_app' = 
      rawChannel === 'in_app' || rawChannel === 'inapp' ? 'in_app' :
      rawChannel === 'email' ? 'email' :
      rawChannel === 'sms' ? 'sms' : 'whatsapp';

    const rawStatus = (l.status || 'sent').toLowerCase();
    const validStatus: 'queued' | 'sent' | 'delivered' | 'read' | 'failed' = 
      rawStatus === 'read' ? 'read' :
      rawStatus === 'delivered' ? 'delivered' :
      rawStatus === 'failed' ? 'failed' :
      rawStatus === 'queued' ? 'queued' : 'sent';

    return {
      id: l.id,
      tenantId: l.tenantId,
      channel: validChannel,
      recipient: l.recipient || l.recipientContact || (l.recipientName ? `${l.recipientName} (${l.recipientContact})` : 'N/A'),
      recipientName: l.recipientName,
      recipientContact: l.recipientContact,
      subject: l.subject,
      content: l.content || '',
      status: validStatus,
      referenceType: l.referenceType,
      referenceId: l.referenceId,
      sentAt: l.sentAt || new Date().toISOString(),
      deliveredAt: l.deliveredAt,
      error: l.errorMessage || l.error,
    };
  };

  const fetchTemplates = async () => {
    try {
      const res = await fetch('/api/v1/communication/templates', {
        headers: getAuthHeaders(),
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && Array.isArray(json.data) && json.data.length > 0) {
          setTemplates(json.data.map(normalizeTemplate));
        }
      }
    } catch (e) {
      console.error('Failed to load templates', e);
    }
  };

  const fetchLogs = async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/v1/communication/logs?limit=100', {
        headers: getAuthHeaders(),
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && Array.isArray(json.data) && json.data.length > 0) {
          setLogs(json.data.map(normalizeLog));
        }
      }
    } catch (e) {
      console.error('Failed to load logs', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTemplates();
    fetchLogs();
  }, []);

  const handleTemplateSelect = (tmplId: string) => {
    setSelectedTemplateId(tmplId);
    const tmpl = templates.find((t) => t.id === tmplId);
    if (tmpl) {
      setChannel(tmpl.channel);
      if (tmpl.subject) setSubject(tmpl.subject);
      setContent(tmpl.body || tmpl.content || '');
      info(`Loaded template: ${tmpl.name}`, 'Template Applied');
    }
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!recipient.trim() || !content.trim()) {
      warning('Please provide recipient details and message body', 'Missing Fields');
      return;
    }

    const confirmed = await confirm({
      title: 'Confirm Message Dispatch',
      message: `Are you sure you want to send this ${channel.toUpperCase()} message to ${recipient}?`,
      type: 'info',
      confirmText: 'Dispatch Message',
    });

    if (!confirmed) return;

    try {
      setSending(true);
      const res = await fetch('/api/v1/communication/send', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          channel: channel.toUpperCase(),
          recipient,
          recipientContact: recipient,
          recipientName: recipient.includes('@') ? recipient.split('@')[0] : 'Authorized Contact',
          templateId: selectedTemplateId || undefined,
          subject: channel === 'email' || channel === 'in_app' ? subject : undefined,
          content,
          variables: {
            companyName: 'Apex Industries Ltd.',
            partyName: 'Customer / Supplier',
            docNumber: 'DOC-2026-001',
            amount: '1,50,000.00',
            date: new Date().toLocaleDateString('en-IN'),
          },
        }),
      });

      const json = await res.json();
      if (json.success) {
        success(`${channel.toUpperCase()} message dispatched successfully to ${recipient}!`, 'Message Sent');
        setContent('');
        setRecipient('');
        setSubject('');
        setSelectedTemplateId('');
        fetchLogs();
      } else {
        error(json.error || 'Failed to dispatch message', 'Dispatch Error');
      }
    } catch (err: any) {
      error(err.message || 'Network error sending communication', 'Error');
    } finally {
      setSending(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'read':
        return (
          <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-950/60 px-2 py-0.5 rounded-full border border-indigo-200 dark:border-indigo-800">
            <CheckCheck className="w-3 h-3 text-indigo-500" /> Read
          </span>
        );
      case 'delivered':
        return (
          <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/60 px-2 py-0.5 rounded-full border border-emerald-200 dark:border-emerald-800">
            <Check className="w-3 h-3 text-emerald-500" /> Delivered
          </span>
        );
      case 'sent':
        return (
          <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300 bg-blue-50 dark:bg-blue-950/60 px-2 py-0.5 rounded-full border border-blue-200 dark:border-blue-800">
            <Clock className="w-3 h-3 text-blue-500" /> Sent
          </span>
        );
      case 'failed':
        return (
          <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-rose-700 dark:text-rose-300 bg-rose-50 dark:bg-rose-950/60 px-2 py-0.5 rounded-full border border-rose-200 dark:border-rose-800">
            <AlertCircle className="w-3 h-3 text-rose-500" /> Failed
          </span>
        );
      default:
        return (
          <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-full border border-slate-200 dark:border-slate-700">
            <Clock className="w-3 h-3" /> Queued
          </span>
        );
    }
  };

  const getChannelIcon = (ch: string) => {
    switch (ch.toLowerCase()) {
      case 'whatsapp':
        return <Smartphone className="w-4 h-4 text-emerald-500" />;
      case 'sms':
        return <MessageSquare className="w-4 h-4 text-amber-500" />;
      case 'email':
        return <Mail className="w-4 h-4 text-blue-500" />;
      case 'in_app':
      case 'inapp':
        return <Bell className="w-4 h-4 text-indigo-500" />;
      default:
        return <Send className="w-4 h-4 text-slate-500" />;
    }
  };

  const query = (searchLog || '').toLowerCase();
  const filteredLogs = useMemo(() => {
    return (logs || []).filter((l) => {
      if (!l) return false;
      const recipientStr = (l.recipient || l.recipientContact || '').toLowerCase();
      const contentStr = (l.content || '').toLowerCase();
      const subjectStr = (l.subject || '').toLowerCase();
      const ch = (l.channel || '').toLowerCase();
      const statusStr = (l.status || '').toLowerCase();

      const matchesSearch =
        searchLog === '' ||
        recipientStr.includes(query) ||
        contentStr.includes(query) ||
        subjectStr.includes(query) ||
        ch.includes(query) ||
        statusStr.includes(query);

      const matchesChannel = logChannelFilter === 'all' || ch === logChannelFilter;
      return matchesSearch && matchesChannel;
    });
  }, [logs, query, logChannelFilter, searchLog]);

  const filteredTemplates = useMemo(() => {
    return (templates || []).filter((t) => {
      if (!t) return false;
      const q = searchTemplate.toLowerCase();
      return (
        searchTemplate === '' ||
        t.name.toLowerCase().includes(q) ||
        (t.subject && t.subject.toLowerCase().includes(q)) ||
        (t.body && t.body.toLowerCase().includes(q)) ||
        (t.category && t.category.toLowerCase().includes(q)) ||
        t.channel.toLowerCase().includes(q)
      );
    });
  }, [templates, searchTemplate]);

  return (
    <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-5 font-sans">
      {/* Top Banner */}
      <div className="finstaq-banner">
        <div className="flex items-center gap-3.5">
          <div className="finstaq-banner-icon">
            <Send className="w-7 h-7" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
                Communication Engine & Alerts
              </h1>
              <span className="px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded-full bg-indigo-100 text-indigo-800 dark:bg-indigo-900/50 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
                Omni-Channel Gateway
              </span>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Multi-channel notifications (WhatsApp, SMS, Email, In-App) & automated transactional messaging
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <button
            type="button"
            onClick={() => {
              fetchLogs();
              fetchTemplates();
            }}
            disabled={loading}
            className="finstaq-btn-secondary"
            title="Refresh logs & templates"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span>Refresh</span>
          </button>
        </div>
      </div>

      {/* Top Executive KPI Grid */}
      <KPIGrid cols={4}>
        <KPIScorecard
          label="TOTAL TRANSMISSIONS"
          value={`${logs.length} Messages`}
          icon={<Send className="w-4 h-4 text-indigo-500" />}
          badge="Audit Logged"
          badgeVariant="indigo"
          footerLeft="Dispatch Scope:"
          footerRight="All Gateways"
        />
        <KPIScorecard
          label="DELIVERY SUCCESS"
          value={logs.length > 0 ? `${(((logs.filter(l => l.status === 'delivered' || l.status === 'read').length) / logs.length) * 100).toFixed(1)}%` : '100%'}
          variant="emerald"
          icon={<CheckCircle2 className="w-4 h-4 text-emerald-500" />}
          badge="High Reliability"
          badgeVariant="emerald"
          footerLeft="Failures / Bounces:"
          footerRight={`${logs.filter(l => l.status === 'failed').length} Failed`}
        />
        <KPIScorecard
          label="ACTIVE CHANNELS"
          value="4 Gateways"
          variant="default"
          icon={<Zap className="w-4 h-4 text-amber-500" />}
          badge="WhatsApp & SMS"
          badgeVariant="amber"
          footerLeft="Protocols:"
          footerRight="HTTP API / SMTP"
        />
        <KPIScorecard
          label="MESSAGE TEMPLATES"
          value={`${templates.length} Templates`}
          variant="indigo"
          icon={<FileText className="w-4 h-4 text-blue-500" />}
          badge="Pre-Configured"
          badgeVariant="blue"
          footerLeft="Dynamic Scope:"
          footerRight="MCA Compliant"
        />
      </KPIGrid>

      {/* Tabs */}
      <StandardTabs<'send' | 'logs' | 'templates'>
        activeTab={activeTab}
        onChange={setActiveTab}
        tabs={[
          {
            id: 'send',
            label: 'Quick Dispatch Studio',
            icon: Send,
          },
          {
            id: 'logs',
            label: 'Delivery & Audit Logs',
            icon: Clock,
            badge: logs.length,
            badgeVariant: 'default',
          },
          {
            id: 'templates',
            label: 'Message Templates',
            icon: FileText,
            badge: templates.length,
            badgeVariant: 'default',
          },
        ]}
      />

      {/* Tab Content 1: Quick Dispatch Studio */}
      {activeTab === 'send' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          <div className="lg:col-span-2 finstaq-card p-4 sm:p-5 space-y-4">
            <h2 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2 pb-2 border-b border-slate-200 dark:border-slate-800">
              <Send className="w-4 h-4 text-indigo-600" />
              <span>Compose & Dispatch Transactional Message</span>
            </h2>

            <form onSubmit={handleSendMessage} className="space-y-3.5">
              {/* Channel Selector */}
              <div>
                <label className="finstaq-label">Select Delivery Channel</label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                  {[
                    { id: 'whatsapp', label: 'WhatsApp', icon: <Smartphone className="w-4 h-4 text-emerald-500" /> },
                    { id: 'sms', label: 'SMS Gateway', icon: <MessageSquare className="w-4 h-4 text-amber-500" /> },
                    { id: 'email', label: 'Email Dispatch', icon: <Mail className="w-4 h-4 text-blue-500" /> },
                    { id: 'in_app', label: 'In-App Alert', icon: <Bell className="w-4 h-4 text-indigo-500" /> },
                  ].map((ch) => (
                    <button
                      key={ch.id}
                      type="button"
                      onClick={() => setChannel(ch.id as any)}
                      className={`flex items-center justify-center gap-1.5 p-2.5 rounded-lg border font-bold text-xs transition-all cursor-pointer ${
                        channel === ch.id
                          ? 'border-indigo-600 bg-indigo-50/50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 ring-2 ring-indigo-500/20'
                          : 'border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800/50'
                      }`}
                    >
                      {ch.icon}
                      <span>{ch.label}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Template quick-loader */}
              <div>
                <label className="finstaq-label">Load from Template (Optional)</label>
                <select
                  value={selectedTemplateId}
                  onChange={(e) => handleTemplateSelect(e.target.value)}
                  className="finstaq-select"
                >
                  <option value="">-- Choose a standard ERP Template --</option>
                  {templates.map((t) => (
                    <option key={t.id} value={t.id}>
                      {t.name} ({t.channel.toUpperCase()})
                    </option>
                  ))}
                </select>
              </div>

              {/* Recipient */}
              <div>
                <label className="finstaq-label">
                  Recipient ({channel === 'email' ? 'Email Address' : channel === 'in_app' ? 'User ID / Email' : 'Mobile Number with Country Code'})
                </label>
                <input
                  type={channel === 'email' ? 'email' : 'text'}
                  required
                  placeholder={channel === 'email' ? 'finance@customer.com' : channel === 'in_app' ? 'admin@apex.finstaq.com' : '+91 98765 43210'}
                  value={recipient}
                  onChange={(e) => setRecipient(e.target.value)}
                  className="finstaq-input"
                />
              </div>

              {/* Subject (for email / in_app) */}
              {(channel === 'email' || channel === 'in_app') && (
                <div>
                  <label className="finstaq-label">Subject Line</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Tax Invoice #INV-2026-089 Dispatched"
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    className="finstaq-input"
                  />
                </div>
              )}

              {/* Body */}
              <div>
                <label className="finstaq-label">Message Content / Body</label>
                <textarea
                  rows={5}
                  required
                  placeholder="Type message content or use template placeholders like {{partyName}}, {{docNumber}}, {{amount}}..."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  className="finstaq-textarea font-mono"
                />
              </div>

              {/* Submit Button */}
              <div className="pt-1">
                <button
                  type="submit"
                  disabled={sending}
                  className="finstaq-btn-primary px-6"
                >
                  <Send className={`w-3.5 h-3.5 ${sending ? 'animate-spin' : ''}`} />
                  <span>{sending ? 'Dispatching Message...' : `Dispatch ${channel.toUpperCase()}`}</span>
                </button>
              </div>
            </form>
          </div>

          {/* Quick Info & Test Toasts/Alerts Panel */}
          <div className="space-y-4">
            <div className="finstaq-card p-4 space-y-3">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                Live UI Feedback Preview
              </h3>
              <p className="text-[11px] text-slate-500">
                Test interactive Toasters and confirmation dialogs:
              </p>
              
              <div className="space-y-2">
                <button
                  type="button"
                  onClick={() => success('Sales Order #SO-2026-099 posted & stock allocated!', 'Order Placed')}
                  className="w-full text-left p-2 rounded-lg text-xs font-semibold bg-emerald-50 hover:bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300 border border-emerald-200/60 dark:border-emerald-800/40 transition cursor-pointer"
                >
                  🟢 Trigger Success Toast
                </button>
                <button
                  type="button"
                  onClick={() => error('Debit and Credit totals do not match! Difference of ₹ 5,000.00 detected.', 'Sanity Check Failed')}
                  className="w-full text-left p-2 rounded-lg text-xs font-semibold bg-rose-50 hover:bg-rose-100 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300 border border-rose-200/60 dark:border-rose-800/40 transition cursor-pointer"
                >
                  🔴 Trigger Error Toast
                </button>
                <button
                  type="button"
                  onClick={() => warning('Minimum stock threshold reached for item STEEL-ROD-10MM', 'Low Stock Alert')}
                  className="w-full text-left p-2 rounded-lg text-xs font-semibold bg-amber-50 hover:bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300 border border-amber-200/60 dark:border-amber-800/40 transition cursor-pointer"
                >
                  🟡 Trigger Warning Toast
                </button>
                <button
                  type="button"
                  onClick={async () => {
                    const ok = await confirm({
                      title: 'Reverse Auto-Posted Voucher?',
                      message: 'This will generate an offsetting Adjustment JV (JV-ADJ) linked directly to the original voucher. Are you sure you want to proceed?',
                      type: 'warning',
                      confirmText: 'Yes, Create Adjustment JV',
                      cancelText: 'Abort',
                    });
                    if (ok) {
                      success('Adjustment JV posted successfully!', 'Reversed');
                    }
                  }}
                  className="w-full text-left p-2 rounded-lg text-xs font-semibold bg-indigo-50 hover:bg-indigo-100 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300 border border-indigo-200/60 dark:border-indigo-800/40 transition cursor-pointer"
                >
                  ✨ Test Confirmation Dialog
                </button>
              </div>
            </div>

            <div className="finstaq-card p-4 space-y-2 bg-slate-50/50 dark:bg-slate-900/50">
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                Supported Placeholders
              </h3>
              <ul className="text-[11px] text-slate-500 dark:text-slate-400 space-y-1 font-mono">
                <li>• {'{{companyName}}'} - Apex Industries Ltd.</li>
                <li>• {'{{partyName}}'} - Supplier / Customer Name</li>
                <li>• {'{{docNumber}}'} - Invoice / PO / Order No.</li>
                <li>• {'{{amount}}'} - Total Document Value</li>
                <li>• {'{{date}}'} - Current Timestamp</li>
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Tab Content 2: Delivery & Audit Logs */}
      {activeTab === 'logs' && (
        <div className="finstaq-card overflow-hidden space-y-3 p-4 sm:p-5">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-200 dark:border-slate-800">
            <div className="relative flex-1 max-w-sm">
              <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Search recipient, content, channel..."
                value={searchLog}
                onChange={(e) => setSearchLog(e.target.value)}
                className="finstaq-input pl-8 py-1.5 text-xs"
              />
            </div>

            <div className="flex items-center gap-2 flex-wrap">
              {/* Channel Filter Pills */}
              <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-0.5 rounded-lg text-[11px] font-bold">
                {['all', 'whatsapp', 'sms', 'email', 'in_app'].map((ch) => (
                  <button
                    key={ch}
                    type="button"
                    onClick={() => setLogChannelFilter(ch)}
                    className={`px-2 py-1 rounded-md transition uppercase text-[9px] font-bold ${
                      logChannelFilter === ch
                        ? 'bg-white dark:bg-slate-900 text-indigo-600 shadow-xs'
                        : 'text-slate-600 dark:text-slate-400'
                    }`}
                  >
                    {ch === 'in_app' ? 'In-App' : ch}
                  </button>
                ))}
              </div>
              <span className="text-[11px] text-slate-400 font-medium">
                {filteredLogs.length} transmissions
              </span>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="finstaq-table">
              <thead>
                <tr>
                  <th className="finstaq-th">Channel</th>
                  <th className="finstaq-th">Recipient</th>
                  <th className="finstaq-th">Message / Subject</th>
                  <th className="finstaq-th">Status</th>
                  <th className="finstaq-th whitespace-nowrap">Dispatched At</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {filteredLogs.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="p-8 text-center text-slate-400 font-medium">
                      <Send className="w-8 h-8 mx-auto mb-2 opacity-30" />
                      <p className="font-bold text-xs">No communication records found</p>
                      <p className="text-[11px] mt-0.5">Dispatched messages will automatically log delivery status here.</p>
                    </td>
                  </tr>
                ) : (
                  filteredLogs.map((log) => (
                    <tr key={log.id} className="finstaq-tr">
                      <td className="finstaq-td whitespace-nowrap">
                        <span className="flex items-center gap-1.5 font-bold uppercase text-[10px]">
                          {getChannelIcon(log.channel)}
                          <span>{log.channel}</span>
                        </span>
                      </td>
                      <td className="finstaq-td font-semibold text-slate-800 dark:text-slate-200">
                        {log.recipient}
                      </td>
                      <td className="finstaq-td max-w-sm">
                        {log.subject && (
                          <div className="font-bold text-slate-900 dark:text-white truncate">{log.subject}</div>
                        )}
                        <div className="text-slate-500 dark:text-slate-400 truncate">{log.content}</div>
                      </td>
                      <td className="finstaq-td whitespace-nowrap">
                        {getStatusBadge(log.status)}
                      </td>
                      <td className="finstaq-td text-slate-500 dark:text-slate-400 whitespace-nowrap font-mono text-[11px]">
                        {new Date(log.sentAt).toLocaleString('en-IN', {
                          day: '2-digit',
                          month: 'short',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Tab Content 3: Message Templates */}
      {activeTab === 'templates' && (
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-slate-900 p-3.5 rounded-xl border border-slate-200 dark:border-slate-800">
            <div className="relative flex-1 max-w-sm">
              <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Search templates by name, variable..."
                value={searchTemplate}
                onChange={(e) => setSearchTemplate(e.target.value)}
                className="finstaq-input pl-8 py-1.5 text-xs"
              />
            </div>
            <span className="text-[11px] font-bold text-slate-500">
              {filteredTemplates.length} Templates Configured
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredTemplates.map((tmpl) => (
              <div
                key={tmpl.id}
                className="finstaq-card p-4 flex flex-col justify-between space-y-3 hover:border-indigo-400 transition"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between gap-2">
                    <span className="flex items-center gap-1.5 text-xs font-bold text-slate-800 dark:text-white truncate">
                      {getChannelIcon(tmpl.channel)}
                      <span>{tmpl.name}</span>
                    </span>
                    <span className="text-[9px] font-bold uppercase px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 shrink-0">
                      {tmpl.channel}
                    </span>
                  </div>

                  {tmpl.subject && (
                    <p className="text-[11px] font-semibold text-indigo-600 dark:text-indigo-400 truncate">
                      Subject: {tmpl.subject}
                    </p>
                  )}

                  <div className="p-2.5 bg-slate-50 dark:bg-slate-950 rounded-lg text-[11px] text-slate-600 dark:text-slate-300 font-mono leading-relaxed whitespace-pre-wrap border border-slate-200/60 dark:border-slate-800 max-h-36 overflow-y-auto">
                    {tmpl.body || tmpl.content}
                  </div>
                </div>

                <div className="pt-2.5 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
                  <span className="text-[10px] text-slate-400 font-mono">
                    {tmpl.variables.length} variables
                  </span>
                  <button
                    type="button"
                    onClick={() => {
                      handleTemplateSelect(tmpl.id);
                      setActiveTab('send');
                    }}
                    className="finstaq-btn-primary py-1 px-3 text-[11px]"
                  >
                    <span>Use Template</span>
                    <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default CommunicationHub;
